name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
      - run: rustup component add clippy rustfmt llvm-tools
      - run: cargo install grcov
      - run: cargo install just
      - run: cargo fmt --check
      - run: just clippy coverage
