name: Zizmor

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: zizmorcore/zizmor-action@v0
        with:
          inputs: .gitea/workflows/* .github
          advanced-security: false
          annotations: true
